### PR TITLE
support for build on mac

### PR DESCRIPTION
**Pull request by rgiduthuri**
I had to redo the porting locally to mac for my development after the recent push.
It will be very helpful if these changes can be absorbed into the develop tree.
Thanks.

### CODE REVIEW

**Comment by newling** [comment]
If I build and install rg/mac-build-fix2, 
```
git checkout rg/mac-build-fix2
sudo make install -j5
```

And then try and build MIOpen,

```
mkdir build2
cd build2
cmake ..
```

The configure step breaks.

```
-- MIOpen_VERSION= 1.0.2
-- CMAKE_BUILD_TYPE= Release
-- MIOpen linking OpenCL: /opt/rocm/opencl/include
-- Configuring done
CMake Error in src/CMakeLists.txt:
  Imported target "miopengemm" includes non-existent path

    "/opt/rocm/opencl/include/Headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.



CMake Error in src/CMakeLists.txt:
  Imported target "miopengemm" includes non-existent path

    "/opt/rocm/opencl/include/Headers"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by rgiduthuri** [comment]
I'll try to fix it and make another commit.  I can also move all platform specific include files into some platform.h file so that my code changes doesn't look ugly. Will you be ok with me adding another header file?

**Comment by newling** [comment]
Thanks for investigating. I don't mind the code changes as they are, either way's fine by me. If you choose the header option,  please use extension hpp for consistency.

**Comment by rgiduthuri** [comment]
@newling committed the changes and checked with a ROCm build too.
Let me know if it works for you.

**Comment by newling** [comment]
@rgiduthuri it's working fine on my end, merged it. Actually I like the `platform.hpp` solution, this way it's difficult to forget about mac builds next time the opencl header is included.

**Pull request merged**
